import initAccordion from "../js/modules/accordion.js";
import initAnimacaoScroll from "../js/modules/scroll-animacao.js";
import initScrollSuave from "../js/modules/scroll-suave.js";
import initTabNav from "../js/modules/tab-nav.js";
import initModal from '../js/modules/modal.js';
initAccordion();
initAnimacaoScroll();
initScrollSuave();
initTabNav();
initModal();
